// src/lib/constants.ts

export const DEPARTMENT_SKILLS_MAP: Record<string, string[]> = {
  "مهندسی نرم‌افزار": [
    "React",
    "Node.js",
    "Python",
    "Java",
    "Spring Boot",
    "Docker",
    "CI/CD",
    "Microservices",
  ],
  "هوش مصنوعی": [
    "Python",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "NLP",
    "Computer Vision",
    "Deep Learning",
    "Reinforcement Learning",
  ],
  "شبکه‌های کامپیوتری": [
    "Cisco",
    "CCNA",
    "TCP/IP",
    "Network Security",
    "SDN",
    "Wireshark",
    "Routing Protocols",
  ],
  "معماری سیستم‌های کامپیوتری": [
    "Verilog",
    "VHDL",
    "FPGA",
    "Computer Architecture",
    "Digital Design",
    "Assembly",
    "Embedded Systems",
  ],
  "امنیت اطلاعات": [
    "Cybersecurity",
    "Penetration Testing",
    "Cryptography",
    "Network Security",
    "Kali Linux",
    "OWASP",
    "SIEM",
  ],
  "علوم داده": [
    "Python",
    "R",
    "SQL",
    "Data Visualization",
    "Machine Learning",
    "Statistics",
    "Big Data",
    "Hadoop",
    "Spark",
  ],
};
