"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { TopBar } from "@/components/layout/TopBar";
import { Card, CardBody } from "@/components/ui/Card";
import { PROJECT_TYPES, PROJECT_TYPE_LABELS } from "@/lib/validation";
import { useAuth } from "@/contexts/AuthContext";

export default function NewProjectPage(){
 const router=useRouter(); const {user}=useAuth(); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 const [form,setForm]=useState({title:"",description:"",type:"research" as typeof PROJECT_TYPES[number],maxMembers:5,deadline:"",visibility:"public" as "public"|"private"});
 useEffect(()=>{ if(user) setForm(f=>({...f,type:user.role==="student"?"course":"research"})); },[user]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError("");setLoading(true);try{const res=await fetch("/api/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,deadline:form.deadline||null})});const data=await res.json();if(!res.ok)throw new Error(data.error||"ساخت پروژه ناموفق بود");router.push(`/dashboard/projects/${data.project.id}`);}catch(e){setError(e instanceof Error?e.message:"ساخت پروژه ناموفق بود");}finally{setLoading(false)}};
 return <div><TopBar title="پروژه جدید" subtitle="یک پروژه جدید ایجاد کنید"/><div className="p-6 max-w-2xl"><Card><CardBody className="p-6"><form onSubmit={submit} className="space-y-4"><Input label="عنوان پروژه" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/><div><label className="block text-sm font-medium mb-1">توضیحات</label><textarea rows={4} className="w-full border rounded-lg px-3 py-2" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} required/></div><div><label className="block text-sm font-medium mb-1">نوع پروژه</label><select className="w-full border rounded-lg px-3 py-2 text-sm bg-white" value={form.type} onChange={e=>setForm({...form,type:e.target.value as any})}>{PROJECT_TYPES.map(t=><option key={t} value={t}>{PROJECT_TYPE_LABELS[t]}</option>)}</select></div><div className="grid grid-cols-2 gap-4"><Input label="حداکثر تعداد اعضا" type="number" min={1} max={10} value={form.maxMembers} onChange={e=>setForm({...form,maxMembers:Number(e.target.value)})} required/><Input label="مهلت انجام" type="date" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})}/></div><div><label className="block text-sm font-medium mb-2">دسترسی پروژه</label><div className="grid grid-cols-2 gap-3"><button type="button" onClick={()=>setForm({...form,visibility:"public"})} className={`rounded-lg border p-3 text-start ${form.visibility==="public"?"border-indigo-500 bg-indigo-50":"border-slate-200"}`}>🌐 <b>عمومی</b><p className="text-xs text-slate-500 mt-1">در فهرست پروژه‌ها نمایش داده می‌شود.</p></button><button type="button" onClick={()=>setForm({...form,visibility:"private"})} className={`rounded-lg border p-3 text-start ${form.visibility==="private"?"border-indigo-500 bg-indigo-50":"border-slate-200"}`}>🔒 <b>خصوصی</b><p className="text-xs text-slate-500 mt-1">فقط افراد دعوت‌شده و اعضا دسترسی دارند.</p></button></div></div>{error&&<div className="bg-red-50 text-red-700 text-sm p-3 rounded-lg border border-red-200">{error}</div>}<div className="flex gap-3 pt-2"><Button type="button" variant="outline" onClick={()=>router.back()}>لغو</Button><Button type="submit" loading={loading}>ساخت پروژه</Button></div></form></CardBody></Card></div></div>
}
