import { NextRequest, NextResponse } from "next/server";
import { db } from "@/db";
import { applications, projects, projectMembers } from "@/db/schema";
import { eq, and } from "drizzle-orm";
import { getAuthUser } from "@/lib/auth";
import { auditLog } from "@/lib/auditLog";
type Params={params:Promise<{id:string;appId:string}>};
export async function PATCH(req:NextRequest,{params}:Params){try{const auth=await getAuthUser();if(!auth)return NextResponse.json({error:"احراز هویت نشده‌اید"},{status:401});const {id,appId}=await params;const projectId=Number(id),applicationId=Number(appId);if(!Number.isInteger(projectId)||projectId<=0||!Number.isInteger(applicationId)||applicationId<=0)return NextResponse.json({error:"شناسه پروژه یا درخواست نامعتبر است"},{status:400});const body=await req.json();const status=body.status;const [app]=await db.select().from(applications).where(and(eq(applications.id,applicationId),eq(applications.projectId,projectId)));if(!app)return NextResponse.json({error:"درخواست یافت نشد"},{status:404});const [project]=await db.select().from(projects).where(and(eq(projects.id,projectId),eq(projects.creatorId,auth.userId)));if(project){if(status!=="approved"&&status!=="rejected")return NextResponse.json({error:"وضعیت نامعتبر است"},{status:400});if(app.status!=="pending")return NextResponse.json({error:"فقط موارد در انتظار قابل تغییرند"},{status:409});if(status==="rejected"){await db.update(applications).set({status:"rejected",updatedAt:new Date()}).where(eq(applications.id,applicationId));auditLog("application_rejected",{applicationId,projectId,studentId:app.studentId,creatorId:auth.userId});return NextResponse.json({message:"درخواست رد شد"});}await db.transaction(async tx=>{const [locked]=await tx.select().from(projects).where(eq(projects.id,projectId)).for("update");const [member]=await tx.select().from(projectMembers).where(and(eq(projectMembers.projectId,projectId),eq(projectMembers.userId,app.studentId)));const members=await tx.select({userId:projectMembers.userId}).from(projectMembers).where(eq(projectMembers.projectId,projectId));const count=members.filter(m=>m.userId!==locked.creatorId).length;if(!member&&count>=locked.maxMembers)throw new Error("PROJECT_FULL");if(!member)await tx.insert(projectMembers).values({projectId,userId:app.studentId});await tx.update(applications).set({status:"approved",updatedAt:new Date()}).where(eq(applications.id,applicationId));if(locked.status==="open")await tx.update(projects).set({status:"in_progress",updatedAt:new Date()}).where(eq(projects.id,projectId));});auditLog("application_approved",{applicationId,projectId,studentId:app.studentId,creatorId:auth.userId});return NextResponse.json({message:"درخواست تأیید شد"});}
if(auth.role==="student"&&app.studentId===auth.userId&&app.source==="student_application"){if(status!=="cancelled")return NextResponse.json({error:"فقط درخواست خود را می‌توانید لغو کنید"},{status:400});if(app.status!=="pending")return NextResponse.json({error:"فقط درخواست در انتظار قابل لغو است"},{status:409});await db.update(applications).set({status:"cancelled",updatedAt:new Date()}).where(eq(applications.id,applicationId));return NextResponse.json({message:"درخواست لغو شد"});}return NextResponse.json({error:"دسترسی مجاز نیست"},{status:403});}catch(e){if(e instanceof Error&&e.message==="PROJECT_FULL")return NextResponse.json({error:"ظرفیت پروژه تکمیل است"},{status:409});console.error("Application PATCH error:",e);return NextResponse.json({error:"خطای داخلی سرور"},{status:500});}}
